name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug", "new"]
assignees:
  - umstek
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com
    validations:
      required: false
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Tell us what happened.
      placeholder: What's wrong?
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Tell us what is expected.
      placeholder: How should it be?
      value: "It should work!"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      placeholder: Version number or commit hash
      value: v6.0.0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What operating systems are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - Linux
        - Mac OS X
        - Other
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome/Edge/Opera
        - Safari
        - Other
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: extra
    attributes:
      label: Anything else?
      description: Other browser or operating system details
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
